steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - kairos
      - --source=.
      - --region=europe-west1
      - --allow-unauthenticated
      - --memory=8Gi
      - --cpu=4
      - --cpu-boost
      - --timeout=3600
      - --min-instances=1
      - --max-instances=1
      - --concurrency=80
      - --session-affinity
      - --project=$PROJECT_ID

options:
  logging: CLOUD_LOGGING_ONLY
